// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -destination=mock_servicer_test.go -package=login -source=handler.go
//

// Package login is a generated GoMock package.
package login

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServicer is a mock of Servicer interface.
type MockServicer struct {
	ctrl     *gomock.Controller
	recorder *MockServicerMockRecorder
	isgomock struct{}
}

// MockServicerMockRecorder is the mock recorder for MockServicer.
type MockServicerMockRecorder struct {
	mock *MockServicer
}

// NewMockServicer creates a new mock instance.
func NewMockServicer(ctrl *gomock.Controller) *MockServicer {
	mock := &MockServicer{ctrl: ctrl}
	mock.recorder = &MockServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicer) EXPECT() *MockServicerMockRecorder {
	return m.recorder
}

// CreateUserAuthToken mocks base method.
func (m *MockServicer) CreateUserAuthToken(ctx context.Context, dto *LoginDTO) (*LoginResultDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAuthToken", ctx, dto)
	ret0, _ := ret[0].(*LoginResultDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserAuthToken indicates an expected call of CreateUserAuthToken.
func (mr *MockServicerMockRecorder) CreateUserAuthToken(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAuthToken", reflect.TypeOf((*MockServicer)(nil).CreateUserAuthToken), ctx, dto)
}
