// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Deadline    *openapi_types.Date `json:"deadline,omitempty"`
	Description *string             `json:"description,omitempty"`
	Title       string              `json:"title"`
}

// CreateTaskResponse defines model for CreateTaskResponse.
type CreateTaskResponse struct {
	Data struct {
		Task Task `json:"task"`
	} `json:"data"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email                string `json:"email"`
	Password             string `json:"password"`
	PasswordConfirmation string `json:"passwordConfirmation"`
}

// CreateUserResponse defines model for CreateUserResponse.
type CreateUserResponse struct {
	Data struct {
		User User `json:"user"`
	} `json:"data"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Message string `json:"message"`
	} `json:"error"`
}

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse struct {
	Data struct {
		User User `json:"user"`
	} `json:"data"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Data struct {
		ExpiresAt time.Time `json:"expiresAt"`
		Token     string    `json:"token"`
		User      User      `json:"user"`
	} `json:"data"`
}

// Task defines model for Task.
type Task struct {
	CreatedAt   time.Time           `json:"created_at"`
	Deadline    *openapi_types.Date `json:"deadline,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          string              `json:"id"`
	IsDone      bool                `json:"is_done"`
	Title       string              `json:"title"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
}

// PostV1AuthLoginJSONRequestBody defines body for PostV1AuthLogin for application/json ContentType.
type PostV1AuthLoginJSONRequestBody = LoginRequest

// PostV1RegistrationJSONRequestBody defines body for PostV1Registration for application/json ContentType.
type PostV1RegistrationJSONRequestBody = CreateUserRequest

// PostV1TasksJSONRequestBody defines body for PostV1Tasks for application/json ContentType.
type PostV1TasksJSONRequestBody = CreateTaskRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYbW/bNhD+Kxw3YF/8ItmOu/rT0iANHAxpkLcOC4KCFs82G4lUyZMTt/B/H46SHctW",
	"7CVL0gbopzjU8fjwuXvuTvrGI5OkRoNGx3vfuIvGkAj/c8+CQDgT7voEvmTgkBZTa1KwqMCbSBAyVhro",
	"N9yKJI2B93graO3Uw1a9HfIaHxqbCOQ9LgUCr3GcpmTj0Co94rMal+Aiq1JURpfdfLQKgRE8C2PQTk2A",
	"SRNlCWgUZM6GxjIcA9s97ld5RoXxCrQ9Qz8QWGrNZ4iw7HDdyazGLXzJlAXJe5eFx6uFmRmQEzprmSyX",
	"Gu2ggi2BYn0Vhbumv79ZGPIe/7V5F5BmEY0m+V0HQ4vrWFas/KH3Iz53YO8NLyRCxWUCxxDH5s8bY2PZ",
	"iExSRXsqnLsxVpY3nkKUWTgunoWt9i/LybHYs8HfntFDRfZrmfJY3ytU5detLW+oPHsbmw+Lf+bAbos/",
	"+V2D6zc+Pv771poNYIEery8n4JwYrahqn4hjyrHFwduonrvZCj+HUYX/APA10f2XGSn9Qyttmxo23Oph",
	"IYDbVFlwu1jVNsJ6+OYsDHrtoBcE/6w2kDqqpLKLoLmGlaoA08Px4CBSH9Rh//xrPzxSfdfXJzvRXr/b",
	"v07/vtg7fNtoNKq8/b8kmaOpLd308YlzVvSHMoeRrzfyk3hKEn/sdq5W8jxstaGz031Thz/eDuphS7br",
	"orPTrXda3W7YCd90giCo9OM+SbNyyaGIHSxsB8bEIPTzzBDKS8+7vcNSWw5oVRacFxn5wCzoPiILHlOL",
	"7qkdGy81q3FHpUrh9JQ0lV9pAMKC3c1wfPff+znuw49nvJbPqD5O/ukdmjFiymfkWOmh8cNVHj6+e9xn",
	"DuzEW0/AOp+ePGwEjYDubFLQIlW8x9t+icoejj2g5iRsigzHzZhqnY+ByUs4RcLHvC95jx8bhxchAfdF",
	"keeMgMN3Rk59sIxG0H6nSNNYRX5v87PLlZLXlW1Vp9RGZmXe0WbgF/Jy7NG3guCpzy6KvT+8pPa8GzCX",
	"RRE4N8xiYrbzhADKI0sFgHdCsoJ1Vmd9PRGxkuzw9MMRM5YlIiYFwMImxxe+HL5zTZlkrPoKcglgZEGC",
	"RiVi5yG1Wi8JKbWG4iUGMbB9jQqnrM4uCFhRloWKQRKwnZeMZV8jWC3iQrcsnwR91ciSRNjpIuGElmwE",
	"yIhbojHHw/ImTBtIwhZGyqFdvD1sEvHJsu3z6Hj97es/iTl8FgAbssOBZUUVXxJ2PH0d0n77cvjoDTFW",
	"EYHLX4dEbEHIKYNb5fCnrh+k61yAYJlgGm5YNh+1Scgo3LXbpuAzb/Sc0l3+LvZdpFv61lTBMz1/xdL9",
	"/l2ZsCnnlB7d01l+Knqroov5nvcuy5P95dXsalnweUoXcsf5106SO2nfNVNrhip/ERtBheoPAC9Calbu",
	"uLB8xjl49cvTfX2zAM0soFUwqZTh60jzoPNyMI8Msvcm04TR0ygNOKYN5p30NWb3QXk4Bek72u9uniF0",
	"7OzfAAAA///aqjY3ihkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
