// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Deadline    *openapi_types.Date `json:"deadline,omitempty"`
	Description *string             `json:"description,omitempty"`
	Title       string              `json:"title"`
}

// CreateTaskResponse defines model for CreateTaskResponse.
type CreateTaskResponse struct {
	Data struct {
		Task Task `json:"task"`
	} `json:"data"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email                string `json:"email"`
	Password             string `json:"password"`
	PasswordConfirmation string `json:"passwordConfirmation"`
}

// CreateUserResponse defines model for CreateUserResponse.
type CreateUserResponse struct {
	Data struct {
		User User `json:"user"`
	} `json:"data"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Message string `json:"message"`
	} `json:"error"`
}

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse struct {
	Data struct {
		User User `json:"user"`
	} `json:"data"`
}

// ListTasksResponse defines model for ListTasksResponse.
type ListTasksResponse struct {
	Data struct {
		Tasks []Task `json:"tasks"`
	} `json:"data"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Data struct {
		ExpiresAt time.Time `json:"expiresAt"`
		Token     string    `json:"token"`
		User      User      `json:"user"`
	} `json:"data"`
}

// Task defines model for Task.
type Task struct {
	CreatedAt   time.Time           `json:"created_at"`
	Deadline    *openapi_types.Date `json:"deadline,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          openapi_types.UUID  `json:"id"`
	IsDone      bool                `json:"is_done"`
	Title       string              `json:"title"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
}

// GetV1TasksParams defines parameters for GetV1Tasks.
type GetV1TasksParams struct {
	// IsDone Filter tasks by completion status. If not provided, returns all tasks (both completed and incomplete).
	IsDone *bool `form:"is_done,omitempty" json:"is_done,omitempty"`
}

// PostV1AuthLoginJSONRequestBody defines body for PostV1AuthLogin for application/json ContentType.
type PostV1AuthLoginJSONRequestBody = LoginRequest

// PostV1RegistrationJSONRequestBody defines body for PostV1Registration for application/json ContentType.
type PostV1RegistrationJSONRequestBody = CreateUserRequest

// PostV1TasksJSONRequestBody defines body for PostV1Tasks for application/json ContentType.
type PostV1TasksJSONRequestBody = CreateTaskRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZf2/bNhD9Khw3YBvgH5LjpKv/Whq0gYOhDdokHVYUBS2ebTYUqZInt27h7z4cJTuy",
	"LTtNmqQ10L8iU+Tx8e7evaPyhSc2zawBg573vnCfjCEV4fHIgUA4E/7yJXzIwSMNZs5m4FBBmCJBSK0M",
	"0DN8Emmmgfd4J+rsN+NOcy/mDT60LhXIe1wKBN7gOM1ojkenzIjPGlyCT5zKUFmzbOa1UwiM4DkYg/Fq",
	"AkzaJE/BoKDpbGgdwzGww9N+nWVUqFegHVl6QGCZs+8hwWWD60ZmDe7gQ64cSN57U1p8u5hmB2SE9qo6",
	"y2fWeKjxlkCxPorCX9Lf3xwMeY//2r4KSLuMRpvsroOhwXUsK7PCppsRn3twG8MLqVB62YFj0Nr+/dE6",
	"LVuJTevcngnvP1onlxe+giR3cFq+izt7v1STY7Fmi70ja4aK5q9lym1tr7iqOG6juqB27+u8ebP45x7c",
	"dfEnu2tww8Lbx/+pc3YLWKDX68MpeC9GK6x6So5jyrPFxte5em7mWvgFjDr8x4C75O5/lEeisb9NfQgP",
	"CiH1X1cpFvsL58S0tnL4bzmLHSnzQ1eN65i95VQ3iw58ypQDf4h1Ehg340dncdTbi3pR9N+qGDZRpbWK",
	"iPYSViocTE/Gg+NEvVAn/fPP/fi56vu+ebmfHPUP+pfZvxdHJ49brVadtW9L+DmaRuWkt0+cs1Lrln2Y",
	"hNop34m7dOKP3ZqolTyPO3vQ3T941IS/Hg+acUfuNUV3/6DZ7RwcxN34UTeKoiriPFe1Wqn8O2lXDj0U",
	"2sNi7sBaDcLcT39UgApmr7A0qgGuy4rzMkNvmBUHt8iK29SmDbVk66FmDe6pdCmcviKOFUcagHDgDnMc",
	"X/16Nsd98vqMN4r+O8QpvL1CM0bM+IwMKzO0QRiK8PHD0z7z4CZh9gScD+nK41bUiujMNgMjMsV7fC8M",
	"URnEcQDUnsRtkeO4ran2hRjYoqRTJELM+5L3+Kn1eBET8FAkeeER8PjEymkIljUIJqwUWaZVEta23/uC",
	"OUWdua4KLcnKbNnv6HIIA0V5Dug7UXTXe5fFP2y+xP5CHZjPkwS8H+aaPNu9QwDL7VgNgCdCstLrrMn6",
	"ZiK0kuzk1YvnzDqWCk0MgMWcAl/8cPjODWWSdeozyArAxIEEg0poHyB1Og8JKXOW4iUGGthTgwqnrMku",
	"CFhZpoXSIAnY/kPGsm8QnBG65C0rutxQNfI0FW66SDhhJBsBMvItubHAwwpRpgVEYQcj5dEtbkbbSPyy",
	"Ovd+eLx+s/wqMsf3AmBLdnhwrKziFWLr6W5Q+/HD4aPbr1YJgSuuekI7EHLK4JPy+JPXN+J1QUBwTDAD",
	"H1k+b72JyIu73ghqCHwMeBGHO2TQcCdSQHCe9958WcHxTGnaIZhjg2noVDUEz3gUmPsW6w+ZsUh93kRJ",
	"kA3mAHNnPBNalwv/GFgcz9eCDLVImfnvP1vhUrDcZFITwT/k4Ka8wY0IncxVH3jl5dVmdPb2PrV97epd",
	"E7owgZzgFExqC8L311IqBsp7ZUYb9ODHSfey+Q25WW1737ylUFdUTnmspBxdmypHA1nyo7FV0+acuD8x",
	"q34F/y5itvRleUP67rCY7QS3fmrcHZG+SOlSAHH+vw0SQGK7b2fODlXxaWKzEFL75k/LmfeoHqvfmTd1",
	"kiXo3ZeQbtR9OJjPLbJnNjeEMbhRWvChMwm95S5m9/Hyda3UsN/9PENo29n/AQAA///n0q6EeB0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
