// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Deadline    *openapi_types.Date `json:"deadline,omitempty"`
	Description *string             `json:"description,omitempty"`
	Title       string              `json:"title"`
}

// CreateTaskResponse defines model for CreateTaskResponse.
type CreateTaskResponse struct {
	Data struct {
		Task Task `json:"task"`
	} `json:"data"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email                string `json:"email"`
	Password             string `json:"password"`
	PasswordConfirmation string `json:"passwordConfirmation"`
}

// CreateUserResponse defines model for CreateUserResponse.
type CreateUserResponse struct {
	Data struct {
		User User `json:"user"`
	} `json:"data"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Message string `json:"message"`
	} `json:"error"`
}

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse struct {
	Data struct {
		User User `json:"user"`
	} `json:"data"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Data struct {
		ExpiresAt time.Time `json:"expiresAt"`
		Token     string    `json:"token"`
		User      User      `json:"user"`
	} `json:"data"`
}

// Task defines model for Task.
type Task struct {
	CreatedAt   time.Time           `json:"created_at"`
	Deadline    *openapi_types.Date `json:"deadline,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          string              `json:"id"`
	IsDone      bool                `json:"is_done"`
	Title       string              `json:"title"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
}

// PostV1AuthLoginJSONRequestBody defines body for PostV1AuthLogin for application/json ContentType.
type PostV1AuthLoginJSONRequestBody = LoginRequest

// PostV1TasksJSONRequestBody defines body for PostV1Tasks for application/json ContentType.
type PostV1TasksJSONRequestBody = CreateTaskRequest

// PostV1UsersJSONRequestBody defines body for PostV1Users for application/json ContentType.
type PostV1UsersJSONRequestBody = CreateUserRequest

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYbU/jOBD+Kz7fSfelL0lbytFPx1YsCjqxaHnZ0yG0cuNp68Wxs/ak0F31v5/spKVp",
	"U7pwwC0SnyjOePz4mXlmJvlOY52kWoFCS3vfqY3HkDD/s2+AIZwxe/0RvmZg0S2mRqdgUIA34cC4FArc",
	"b7hlSSqB9mgraO3Uw1a9HdIaHWqTMKQ9yhkCrVGcps7GohFqRGc1ysHGRqQotCq7+WQEAnHwDIxBWTEB",
	"wnWcJaCQOXMy1IbgGMj+SVTlGQXKFWh97X4gkNToLxBj2eG6k1mNGviaCQOc9i4Lj1cLMz1wTtxZy2TZ",
	"VCsLFWwxZOuryOy1+/ubgSHt0V+bdwFpFtFoOr/rYNziOpYVK3/oZsTnFszG8ELChCwTOAYp9Z832kje",
	"iHVSRXvKrL3Rhpc3nkKcGTgpnoWt9i/LybHYc4+/vlZD4ezXMuWxvleoyq9bW95QefY2Nh8W/8yC2RZ/",
	"53cNrt/4+PgfGKPvAQvu8fpyAtay0YqqDhxxRFiyOHgb1XM3W+HnMKrwHwK+Jrr/0iOhfmqlbVPDPbd6",
	"WAjgNhUG7D5WtY2wHu6ehUGvHfSC4J/VBlJHkVR2EdTXsFIVYHo0HhzG4oM4is6/ReGxiGykPu7E/agb",
	"Xad/X/SP9hqNRpW3/5YkczS1pZs+PnHOiv5Q5jD29YZ/Zk9J4s/dzsVKnoetNnR2urt1+GNvUA9bvF1n",
	"nZ1uvdPqdsNOuNsJgqDSj/3M9colh0xaWNgOtJbA1PPMEMJLz7u9w1JbDmhVFpwXGfnALOg+IgseU4s2",
	"1I57LzWrUetKlcDpqdNUfqUBMANmP8Px3X/v57iPPp3RWj6j+jj5p3doxogpnTnHQg21H67y8NH9k4hY",
	"MBNvPQFjfXrSsBE0AndnnYJiqaA92vZLruzh2ANqTsImy3DclK7W+RjovIS7SPiYR5z26Im2eBE64L4o",
	"0pwRsPhO86kPllYIyu9kaSpF7Pc2v9hcKXld2VZ1Sm1kVuYdTQZ+IS/HHn0rCJ767KLY+8NLas+7AbFZ",
	"HIO1w0w6ZjtPCKA8slQAeMc4KVgndRKpCZOCk6PTD8dEG5Iw6RQAC5scX/hy+M6VyyRtxDfgSwBjAxwU",
	"Ciath9RqvSSk1GgXLzaQQA4UCpySOrlwwIqyzIQE7oDtvGQsI4VgFJOFbkk+CfqqkSUJM9NFwjHFyQiQ",
	"OG4djTkekjdht8FJ2L0t2W3qPfNGz6Pc9dfpH5Jv+CwANtPunpOibi9JWU7fxPxjYnbYhLVCjTYk5JvA",
	"twq8GAto77I8EFxeza6W9Z+nNGFEwQ3B+UcSJ3c3iG+V+7k3ek65L39e+V/kXnpFrsoOC+YVy33v5fD1",
	"tRpKETtw+fcOJg0wPiVwKyy+Ne4HNe6ScLP5m/RCuM3U6KHIX7xGUKHfQ5jL96SwfMa5d/VL0yYZFaCJ",
	"ATQCJpWCeh39Kei8HMxjjeS9zpTD6GnkGixRGnNhvca2dFgeRoH7FP/dzjPEHTv7NwAA///Hqe8qehkA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
